# Generated by Django 3.2.7 on 2021-10-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_alter_upload_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='image2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
