# Generated by Django 3.2.7 on 2021-10-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_alter_upload_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
